name: Generate Documentation

on:
  push:
    branches:
      - main  # or the branch you want to trigger the action on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate documentation
        run: |
          python python/src/gendoc.py


      - name: Add untracked files
        run: |
          git add .

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          COMMIT_HASH=$(git rev-parse HEAD)
          git commit -m "Update documentation for commit $COMMIT_HASH: Docs updated"
          git push
