name: Generate Documentation

on:
  push:
    branches:
      - main  # or the branch you want to trigger the action on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lazydocs numpy pandas  # Add other required modules here

    - name: Set PYTHONPATH
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/python/src

    - name: Generate Documentation
      run: |
        lazydocs python/src --output-path ./docs  # target the entire src directory and output to ./docs

    - name: Commit and Push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ./docs
        git commit -m "Update documentation"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
